version: "3.9"

services:
  postgres:
    container_name: postgres_container
    image: postgres:14
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: CalendarDatabase
      POSTGRES_HOST: postgres

    restart: always

    ports:
        - 5433:5432

    volumes:
      - ./postgres-data:/var/lib/postgresql/data  

      - ./Database/Migrations/0_init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - ./Database/Migrations/1_create_enums.sql:/docker-entrypoint-initdb.d/1_create_enums.sql
      - ./Database/Migrations/2_create_tables.sql:/docker-entrypoint-initdb.d/2_create_tables.sql
      - ./Database/Migrations/3_creating_indexes.sql:/docker-entrypoint-initdb.d/3_creating_indexes.sql
      - ./Database/Migrations/4_data_feed.sql:/docker-entrypoint-initdb.d/4_data_feed.sql

    networks:
      - postgres

  todocalendar-app:
    build:
        context: .
        dockerfile: ./ToDoCalendarServer/Dockerfile

    container_name: todocalendar-app

    image: todocalendar

    ports:
       - 5000:80

    restart: always

    depends_on:
     - postgres

    networks:
      - postgres


networks:
  postgres:
    driver: bridge