version: "3.9"

services:
  postgres:
    container_name: postgres_container
    image: postgres:14
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: OrganizerDatabase
      POSTGRES_HOST: postgres
    ports:
        - 5432:5432
    volumes:
      - ./Database/Migrations/:/docker-entrypoint-initdb.d/
    networks:
      - internal
    restart: always

  redis:
    container_name: redis_container  
    image: redis:6.2-alpine
    environment:
        REDIS_HOST: redis
    ports:
        - '6379:6379'
    volumes: 
      - ./Database/Cache/:/data
    networks:
        - internal
    restart: on-failure

  organizer-app:
    build:
        context: .
        dockerfile: ./OrganizerServer/Dockerfile
    container_name: organizer-app
    image: organizer
    ports:
       - 3500:8080
    depends_on:
     - postgres
     - redis 
    networks:
      - internal
    restart: always


networks:
  internal:
    driver: bridge