CREATE TABLE alerts (
	id integer GENERATED BY DEFAULT AS IDENTITY,
	title text NOT NULL,
        description text NOT NULL,
        moment timestamp with time zone NOT NULL,
        is_alerted boolean NOT NULL,
        CONSTRAINT pk_alerts PRIMARY KEY (id));